# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNM9b7HdjBytsit1B35NpYsYloJ6X1B2
"""

from sympy import *
import sympy as sp

def Rotx(theta):
  return Matrix([
                 [1,          0,           0],
                 [0, cos(theta), -sin(theta)],
                 [0, sin(theta),  cos(theta)]
                 ])
def Rotz(theta):
  return Matrix([
                 [cos(theta), -sin(theta), 0],
                 [sin(theta),  cos(theta), 0],
                 [0,                    0, 1]
                 ])
def Roty(theta):
  return Matrix([
                 [ cos(theta), 0, sin(theta)],
                 [          0, 1,          0],
                 [-sin(theta), 0, cos(theta)]
                 ])

def DH(a, d, alpha, theta):
  Rz = Rotz(theta)
  Rx = Rotx(alpha)
  Pz = Matrix([0,0,d])
  Px = Matrix([a,0,0])
  null_row = Matrix([[0,0,0,1]])
  return Rz.row_join(Pz).col_join(null_row) * Rx.row_join(Px).col_join(null_row)

def Get_functions():
  theta1, theta2, theta3, theta4, theta5, theta6, theta7 = symbols("theta1 theta2 theta3 theta4 theta5 theta6 theta7")
  q = Matrix([theta1, theta2, theta3, theta4, theta5, theta6, theta7])

  DHtable = Matrix([
      [0      , 0.333,     0, theta1],
      [0      , 0    , -pi/2, theta2],
      [0      , 0.316,  pi/2, theta3],
      [0.0825 , 0    ,  pi/2, theta4],
      [-0.0825, 0.384, -pi/2, theta5],
      [0      , 0    ,  pi/2, theta6],
      [0.088  , 0    ,  pi/2, theta7],
      [0      , 0.107,     0,      0]
  ])
  DHtable

  DH(*DHtable[0,0:4])

  DHtable.row(0)

  L = int(DHtable.__len__()/4)
  Zaxis = zeros(3,L)
  FK = eye(4)

  for i in range(L):
    T = DH(*DHtable.row(i))
    #T = DH(0,10,0,0)
    FK = FK * T

    Zaxis[0,i] = FK[0,2]
    Zaxis[1,i] = FK[1,2]
    Zaxis[2,i] = FK[2,2]

  FK.__len__()

  EEF = FK[0:3,3]
  ROT = FK[0:3,0:3]

  Jp = EEF.jacobian(q)

  Zaxis.col_del(-1)
  Jr = Zaxis

  J = Jp.col_join(Jr)
  J.shape

  fk  = lambdify(q,FK)
  eef = lambdify(q,EEF)
  rot = lambdify(q,ROT) 
  j   = lambdify(q,J)

  return fk, eef, rot, j

